#==============================================================================
#   Copyright (c) 2016-2019 Nikita Kniazev
#
#   Use, modification and distribution is subject to the Boost Software
#   License, Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
#   http://www.boost.org/LICENSE_1_0.txt)
#==============================================================================

language: cpp

addon_shortcuts:
  clang-7: &clang-7
    apt:
      sources:
        - llvm-toolchain-xenial-7
        - ubuntu-toolchain-r-test
      packages:
        - clang-7
        - libstdc++-8-dev
        - python-numpy
        - python3-dev
        - python3-numpy

  gcc-8: &gcc-8
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-8
        - python-numpy
        - python3-dev
        - python3-numpy

os: linux
dist: xenial

matrix:
  include:
    - { env: 'STD=17,14  PYTHON=python3',  compiler: clang-7, addons: *clang-7 }
    - { env: 'STD=17,14  PYTHON=python3', compiler: gcc-8, addons: *gcc-8 }
    - { env: 'STD=11,03  PYTHON=python3',  compiler: clang-7, addons: *clang-7 }
    - { env: 'STD=11,03  PYTHON=python3', compiler: gcc-8, addons: *gcc-8 }
    - { env: 'STD=17,14  PYTHON=python',  compiler: clang-7, addons: *clang-7 }
    - { env: 'STD=17,14  PYTHON=python', compiler: gcc-8, addons: *gcc-8 }
    - { env: 'STD=11,03  PYTHON=python',  compiler: clang-7, addons: *clang-7 }
    - { env: 'STD=11,03  PYTHON=python', compiler: gcc-8, addons: *gcc-8 }


install:
  - BOOST_BRANCH=develop && [ "$TRAVIS_BRANCH" == "master" ] && BOOST_BRANCH=master || true
  - cd ..
  - git clone -b $BOOST_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - rm -rf libs/python
  - mv $TRAVIS_BUILD_DIR libs/python
  - ln -s libs/python $TRAVIS_BUILD_DIR
  - git submodule update --init tools/boostdep
  - python tools/boostdep/depinst/depinst.py python
  - ./bootstrap.sh

script:
  - ./b2 -j`nproc` libs/python/test toolset=$TRAVIS_COMPILER cxxstd=$STD
